# Use a full Debian-based image so we can install ffmpeg
FROM n8nio/n8n:latest-debian

USER root

# Install ffmpeg
RUN apt-get update && apt-get install -y ffmpeg

# Switch back to node (n8n requires this)
USER node

# Keep Render env variables available
ENV N8N_BASIC_AUTH_ACTIVE=$N8N_BASIC_AUTH_ACTIVE \
    N8N_BASIC_AUTH_USER=$N8N_BASIC_AUTH_USER \
    N8N_BASIC_AUTH_PASSWORD=$N8N_BASIC_AUTH_PASSWORD \
    DB_TYPE=$DB_TYPE \
    DB_POSTGRESDB_HOST=$DB_POSTGRESDB_HOST \
    DB_POSTGRESDB_PORT=$DB_POSTGRESDB_PORT \
    DB_POSTGRESDB_DATABASE=$DB_POSTGRESDB_DATABASE \
    DB_POSTGRESDB_USER=$DB_POSTGRESDB_USER \
    DB_POSTGRESDB_PASSWORD=$DB_POSTGRESDB_PASSWORD \
    DB_POSTGRESDB_SCHEMA=$DB_POSTGRESDB_SCHEMA \
    N8N_ENCRYPTION_KEY=$N8N_ENCRYPTION_KEY \
    WEBHOOK_TUNNEL_URL=$WEBHOOK_TUNNEL_URL \
    N8N_EDITOR_BASE_URL=$N8N_EDITOR_BASE_URL

# Start n8n
CMD ["n8n"]
